# Generated by Django 4.2.3 on 2023-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
