# Generated by Django 4.2.3 on 2023-07-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_pedidos_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.IntegerField(default=50000),
        ),
    ]
