# Generated by Django 4.2.3 on 2023-07-04 05:30

import aplicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_pedidos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rut',
            field=models.CharField(error_messages='Debe ingresar rut', max_length=10, primary_key=True, serialize=False, validators=[aplicacion.models.rut_validator]),
        ),
    ]
