# Generated by Django 4.2.3 on 2023-07-04 05:32

import aplicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_cuenta_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='rut',
            field=models.CharField(error_messages={'invalid': 'Debe ingresar rut'}, max_length=10, primary_key=True, serialize=False, validators=[aplicacion.models.rut_validator]),
        ),
    ]
