# Generated by Django 4.2.3 on 2023-07-04 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_cuenta_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='direccion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
